version: "3.8"
services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./env-db-prod.env
    ports:
      - "${DATABASE_EXTERNAL_PORT:-5532}:5432"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data/pgdata
      - ./database/backups:/backups
      - ./dev/backup:/backup_scripts
  be:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    env_file:
      - ./env-be-prod.env
    depends_on:
      - db
    ports:
      - "${BACKEND_EXTERNAL_PORT:-3100}:3000"
  php:
    build: ./migration/.
    restart: always
    ports:
      - "${PHP_EXTERNAL_PORT:-8180}:80"
  fe:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always
    depends_on:
      - be
    ports:
      - "${FRONTEND_EXTERNAL_PORT:-8184}:8080"
