name: Runs deployment scripts to set up the stack
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Build and deploy script
        run: ./dev/build/build-and-deploy.bash init

      - name: docker compose up
        run: docker compose up -d

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "10"

      - name: Database backup
        run: ./dev/backup/database-backup.bash

      - name: Check if a backup was created
        run: '[ -n "$(ls ./database/backups/*.sql.gz)" ]'

      - name: Smoke test backend connection
        run: ./dev/ci/backend-smoke-test.bash
