name: Runs deployment scripts to set up the stack
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - run: npm ci

      - name: Run Build and deploy script
        run: ./dev/build/build-and-deploy.bash init

      - name: Prepare smoke test environemnt
        run: ./dev/ci/prepare-smoke-test.bash

      - name: docker compose up
        run: docker compose up -d

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "20"

      - name: Smoke test backend connection
        run: ./dev/ci/backend-smoke-test.bash

      - name: Smoke test backend mutations
        run: npm run smoke-test --workspace=@lebenswurzel/solawi-bedarf-backend
        env:
          SMOKE_BASE_URL: http://0.0.0.0:8184/api

      - name: Database backup
        run: ./dev/backup/database-backup.bash

      - name: Check if a backup was created
        run: '[ -n "$(ls ./database/backups/*.sql.gz)" ]'
